### ISSUE TITLE
Helena NS Portriat Missing - Showing Guildna NS Portrait

### ISSUE THREAD

**Issue by lavar23** [HU-Lee/anothercharcheck#1]
Helena is missing her NS portrait on the Character Checklist. It is replaced by Guildna. When you click the Guildna portrait next to Helena both portraits will light up.

Present on both Global (2.10.200) and Japan (2.11.50)
![Capture](https://user-images.githubusercontent.com/58532668/146670891-c5cfc162-df57-4cc3-ac93-37f9103af4d7.PNG)
![Capture](https://user-images.githubusercontent.com/58532668/146671030-5e9d8aad-30f9-4ab7-aa1f-b059a1e8baff.PNG)

**Comment by HU-Lee** [comment]
I fixed this issue (There's a typo)

If you cannot find any changes, please delete cache and try again
