### ISSUE TITLE
Previously exported data matches incorrect characters

### ISSUE THREAD

**Issue by theultramage** [HU-Lee/anothercharcheck#2]
I last exported my data on 2022-03-26. Today I loaded my exported data, but it's selecting the wrong characters.
I see that https://github.com/HU-Lee/anothercharcheck/commit/48d4426e60377a92f62cd3ce272ec71de06c39f3 re-numbered the characters and added an old-to-new mapping array. Then the Dataloader might need a checkbox to signal if it's old data or new data, at least temporarily.

**Comment by HU-Lee** [comment]
@theultramage 

Hello. and sorry for checking this issue far late.

As you noticed, I've changed some dataset for checklist site and added an old-to-new mapping array,
but it wasn't used on current Dataloader component.

I'm preparing some updates now, and I'll prepare for function to migrate old data on that update too.
Please wait a little.

**Comment by HU-Lee** [comment]
@theultramage 

Hello again. I recently updated site, and I also added the function to migrate old data.
Please give me some feedback if you still have problems with this issue.

**Comment by theultramage** [comment]
Thank you for the update and the fix. I was able to successfully convert my saved data.
