### ISSUE TITLE
Milla's English Name

### ISSUE THREAD

**Issue by CognitiveMango** [HU-Lee/anothercharcheck#3]
Hi, could you please change "Mammy" to "Milla"? That's the correct English name in-game. Thanks in advance.
Wiki Link: https://anothereden.wiki/w/Milla

![Screenshot_20221103-210807_SystemUI](https://user-images.githubusercontent.com/17508434/199766272-c1c6d07b-ba8b-4e68-8107-7add1f979a57.png)

**Comment by HU-Lee** [comment]
> Hi, could you please change "Mammy" to "Milla"? That's the correct English name in-game. Thanks in advance. Wiki Link: https://anothereden.wiki/w/Milla
> 
> ![Screenshot_20221103-210807_SystemUI](https://user-images.githubusercontent.com/17508434/199766272-c1c6d07b-ba8b-4e68-8107-7add1f979a57.png)

Hello.

Thank's for reporting translation issues.
It'll be fixed until this weekend, with Japanese 3.0 additional works.

Since I'm not native english speaker and I cannot check all translation,
You can report other translation issues at any time.
Thank you.

**Comment by CognitiveMango** [comment]
Thank you. All the other translations are correct! 

Do you still play this game? Last time I asked you said you had quit.

**Comment by HU-Lee** [comment]
Sorry for late response.

Milla's issue has fixed, with some additional works.
You can check site after refresh.

PS, I'm still not playing this game... It's over a year I had quit.
But I'm still getting information about game from other source.

**Comment by CognitiveMango** [comment]
Thank you for maintaining this site even though you have quit.
