### ISSUE TITLE
Kumos (buddy) wasn't added alongside Yakumo

### ISSUE THREAD

**Issue by Ilya0S** [HU-Lee/anothercharcheck#4]
Hello, I hope I'm writing in right repository. It's for aecheck.com, right? If not, sorry.

In the latest update for the site, you've added Yakumo, but you forgot his buddy – Kumos. Kumos still shows up only if you choose Japanese version.

**Comment by HU-Lee** [comment]
@Ilya0S 
sorry for the late response... I forgot check this issue.
It was fixed on 2023/06/22, with Japanese Version Update.
I found Kumos was missed and added it.

**Comment by Ilya0S** [comment]
Yeah, I've seen that. Thank you for replying
